### ISSUE TITLE
ST3: ImportError: No module named 'indentation'

### ISSUE THREAD

**Issue by rpardee** [wbond/sublime_alignment#51]
Trying to get up & running w/ST3 & Package Control.  I went to install alignment & the status bar gave a "successfully installed" message, but the commands/menu items are not present.  Looking at the console I find:

```
reloading plugin Alignment.Alignment
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "Alignment in C:\Documents and Settings\pardre1\Application Data\Sublime Text 3\Installed Packages\Alignment.sublime-package", line 10, in <module>
ImportError: No module named 'indentation'
found 5 files for base name Default.sublime-keymap
found 3 files for base name Main.sublime-menu
```

Soooo--missing dependency maybe?  Or is Alignment just not ready for ST3?

Thanks!

-Roy

**Comment by zchrykng** [comment]
Yeah, the "official" version of Alignment is not ready for ST3 yet. There is a pull request open that seems to work for some people if you want to try it.

Also, Abacus does work in ST3 if you want to try it.

**Comment by rpardee** [comment]
Ah, thanks Z.  I'll give abacus a shot.

**Comment by jm3** [comment]
Thanks, will try Abacus as well.

**Comment by rpardee** [comment]
I was hoping alignment would be ST3 compatible by now, but again I have the 'successfully installed' message & again, no menu items.  Is that not a goal?

Thanks!
