### ISSUE TITLE
Alignment not available in Package Control

### ISSUE THREAD

**Issue by iDXs** [wbond/sublime_alignment#64]
I tried this with:
--OS X Mavericks & Sublime Text 3
--Windows 7 & a fresh install of ST3
--Fresh Win8 Install using brand new install of ST3

"Alignment" does not appear in the list of available packages.  =[

**Comment by erikflowers** [comment]
I just installed it via Package Control today. OS X Mavericks with ST 2. 

No idea why I could see it and you couldn't, but I can confirm it was there and did work.

**Comment by findchris** [comment]
I'm seeing the same thing on ST2 (OSX Mavericks).  Cannot find that package by name.
:+1:

**Comment by nilcolor** [comment]
OSX Mavericks, ST3 b3059
Package can be found but can't be installed:

```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "~/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_installer.py", line 241, in run
    self.result = self.manager.install_package(self.package)
  File "~/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/package_manager.py", line 489, in install_package
    package_bytes = download_manager.fetch(url, 'Error downloading package.')
  File "~/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/download_manager.py", line 180, in fetch
    return self.downloader.download(url, error_message, timeout, 3, prefer_cached)
  File "~/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/downloaders/urllib_downloader.py", line 113, in download
    http_file = self.opener.open(request, timeout=timeout)
  File "X/urllib/request.py", line 473, in open
  File "X/urllib/request.py", line 491, in _open
  File "X/urllib/request.py", line 451, in _call_chain
  File "~/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/http/validating_https_handler.py", line 44, in https_open
    return self.do_open(http_class_wrapper, req)
  File "~/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/http/persistent_handler.py", line 94, in do_open
    if r.is_keep_alive():
  File "~/Library/Application Support/Sublime Text 3/Packages/Package Control/package_control/http/debuggable_http_response.py", line 58, in is_keep_alive
    if connection.lower() == 'keep-alive':
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by wbond** [comment]
@nilcolor You have a REALLY old alpha build of Package Control 2. You'll want to wipe that and install fresh.

**Comment by wbond** [comment]
@iDXs Can you provide a Package Control debug log of you trying to install the package?

**Comment by nilcolor** [comment]
@wbond ic... thanks! )

**Comment by whlsxl** [comment]
I have the same problem. I found 'Alignment' on a forum, and I try to install it. But I can't find it in package control.
Final, I found I had install it!

**Comment by wbond** [comment]
For future users, if you can't find it:
1. Make sure it is not already installed
2. Check to see if it is in Preferences > Settings - User under `ignored_packages`
